services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: developer_test