FROM php:8.1.7-apache

RUN a2enmod rewrite
RUN apt-get update
RUN apt-get install -y libzip-dev
RUN docker-php-ext-install pdo pdo_mysql zip

WORKDIR /var/www/html

COPY app app
COPY bootstrap bootstrap
COPY config config
COPY database database
COPY lang lang
COPY public public
COPY resources resources
COPY routes routes
COPY .env.production .env
COPY composer.json composer.json
COPY composer.lock composer.lock
COPY artisan artisan
COPY phpunit.xml phpunit.xml

# install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN composer install -o --no-dev --prefer-dist

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

EXPOSE 80